### ISSUE TITLE
Issue: CSU01 flow

### ISSUE THREAD

**Issue by EnzoTatiyama** [Rafael-Sabugari/Source-Code-Inspection#19]
Caso o usuário insira uma nota inválida é necessário voltar para o passo 1 do fluxo principal

<img width="772" alt="image" src="https://github.com/Rafael-Sabugari/Source-Code-Inspection/assets/77353347/fd52b35d-329e-4c8b-b1e7-794d48cf6764">

**Comment by Rafael-Sabugari** [comment]
![image](https://github.com/Rafael-Sabugari/Source-Code-Inspection/assets/91262894/0c7107cb-2747-4868-b35b-d381e190ad98)
