### ISSUE TITLE
Issue: request ticket

### ISSUE THREAD

**Issue by EnzoTatiyama** [Rafael-Sabugari/Source-Code-Inspection#20]
Na descrição do requisito não informa sobre a ação de solicitar o bilhete

<img width="768" alt="image" src="https://github.com/Rafael-Sabugari/Source-Code-Inspection/assets/77353347/7c45a185-a1f0-4c55-86b1-7ab5dc4a73ad">

**Comment by Rafael-Sabugari** [comment]
![image](https://github.com/Rafael-Sabugari/Source-Code-Inspection/assets/91262894/1d6043d3-233b-40e4-9901-f52ed6ac0ffc)
