### ISSUE TITLE
Issue: Wrong action

### ISSUE THREAD

**Issue by Rafael-Sabugari** [Rafael-Sabugari/Source-Code-Inspection#21]
O sistema deveria devolver o bilhete caso o papel moeda fosse aceito.

![image](https://github.com/Rafael-Sabugari/Source-Code-Inspection/assets/91262894/eedb28e7-0946-491d-9772-3e6c41aae07b)

**Comment by EnzoTatiyama** [comment]
solved:
<img width="906" alt="image" src="https://github.com/Rafael-Sabugari/Source-Code-Inspection/assets/77353347/e83ba981-ea2b-476e-be81-2c06be717afd">
